stages:
  - build

dev:
  stage: build
  image: docker:18.09.4
  only:
    - dev
  tags:
    - docker
  script:
    - docker build -t reg.paradise-soft.com.tw:5000/fileserver-spa .
    - docker push reg.paradise-soft.com.tw:5000/fileserver-spa:latest

tags:
  stage: build
  image: docker:18.09.4
  only:
    - tags
  tags:
    - docker
  script:
    - docker build --build-arg VERSION=$CI_COMMIT_TAG --build-arg COMMITSHA=$CI_COMMIT_SHA -t reg.paradise-soft.com.tw:5000/fileserver-spa:$CI_COMMIT_TAG . 
    - docker push reg.paradise-soft.com.tw:5000/fileserver-spa:$CI_COMMIT_TAG

